name: teste Projeto Ativa
favicon: null
layout_spectrum: 0.20316
typography_spectrum: 0.30531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#6a6b63'
    - '#a69f8c'
    - '#b62b04'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
