name: teste Projeto Ativa
favicon: null
layout_spectrum: 0.2081
typography_spectrum: 0.30283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#515562'
    - '#212121'
    - '#2b99ff'
    - '#008800'
  brandStrength: 0
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
