name: teste Projeto Ativa
favicon: null
layout_spectrum: 0.03134
typography_spectrum: 0.24845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98dad3'
    - '#fa3500'
    - '#ffa366'
    - '#305d7b'
    - '#0ea7b5'
  brandStrength: 0.3125
  lightness: 0.42057045083492994
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
